### ISSUE TITLE
dev-python/django-guardian-1.4.3 build fails due to sandbox violation

### ISSUE THREAD

**Issue by gedia** [ercpe/lh-overlay#29]
```
>>> Compiling source in /var/tmp/portage/dev-python/django-guardian-1.4.3/work/django-guardian-1.4.3 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    cmdclass={'flakes': RunFlakesCommand},
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 316, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 371, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1118, in best_match
    return self.obtain(req, installer)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1130, in obtain
    return installer(requirement)
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 439, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('/var/tmp/portage/dev-python/django-guardian-1.4.3/work/django-guardian-1.4.3-python2_7/pytest_runner.egg-info', 511) {}
```

**Comment by gedia** [comment]
[emerge-info.txt](https://github.com/ercpe/lh-overlay/files/680751/emerge-info.txt)

**Comment by ercpe** [comment]
Could you please attache the `build.log` file?

**Comment by gedia** [comment]
Sure
[django-guardian-build-log.txt](https://github.com/ercpe/lh-overlay/files/681389/django-guardian-build-log.txt)

**Comment by gedia** [comment]
Is this reproducible on your box or is it just me?

**Comment by ercpe** [comment]
I haven't been able to reproduce this error on my systems. From what I can see, this error shouldn't happen as portage should be able to write to this directory.
Could you please attach the output of `emerge --config`?

**Comment by gedia** [comment]
Doesn't emerge --config invoke pkg_config of an ebuild? If you meant emerge --info, this is already uploaded in my second post...

**Comment by gedia** [comment]
I know it doesn't make any sense. Am I right in thinking that it fails during the mkdir:

```
distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('/var/tmp/portage/dev-python/django-guardian-1.4.3/work/django-guardian-1.4.3-python2_7/pytest_runner.egg-info', 511) {}
```

This should definitely be writeable...

**Comment by ercpe** [comment]
Which version of setuptools do you use? Could you please try to update to the lastest stable?

**Comment by gedia** [comment]
I'm running on 30.4.0. I've just downgraded to dev-python/setuptools-28.8.0 and then dev-python/setuptools-20.6.7 and I'm still getting the same issue.

**Comment by gedia** [comment]
Seems like this might be related:

https://bugs.gentoo.org/show_bug.cgi?id=604148

**Comment by jlec** [comment]
@gedia Do other python packages install fine? What is the output of ```eselect python list```? Is the system hit by news item [17](https://www.gentoo.org/support/news-items/2015-12-16-python-abiflags-rebuild-needed.html)?

**Comment by gedia** [comment]
There are several python packages already installed, including django.

The output of ```eselect python list``` is:
```
rincewind ~ # eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.4
  [2]   python3.5
  [3]   python2.7
```

The system was first set up in 2016, and I have emerged -e world recently, so I don't think the news item affects my box...

**Comment by jlec** [comment]
for me it says 
```bash
$ eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.5
  [2]   python3.4 (fallback)
  [3]   python2.7 (fallback)
  [4]   pypy3 (fallback)
  [5]   pypy (fallback)
```

Perhaps you can try set python and try again.

**Comment by gedia** [comment]
I've already done that, no difference whatsoever...

**Comment by jlec** [comment]
Do you have ```easy_install``` in your `PATH` somewhere?

**Comment by gedia** [comment]
Yes:
```
rincewind ~ # equery belongs /usr/bin/easy_install 
 * Searching for /usr/bin/easy_install ... 
dev-python/setuptools-20.6.7 (/usr/bin/easy_install -> ../lib/python-exec/python-exec2)
```

**Comment by jlec** [comment]
@gedia You have some weirdness in your system. Did you ever install something outside portage into sitedir?

**Comment by jlec** [comment]
Actually I have no idea anymore.

**Comment by kiyoya** [comment]
In case you missed it, there is a follow-up at the bug gedia mentioned. The fix is to add `dev-python/pytest-runner` as a dependency.

pytest-runner is not in install_requires but in setup_requires at setup.py.

**Comment by ercpe** [comment]
Thanks for this information.

@gedia I've added `dev-python/pytest-runner` to the 1.4.3 ebuild. Could you please give it a try?

**Comment by gedia** [comment]
It escapes me how a missing dependency can result in sandbox violations, but hey, it works.

Thanks

**Comment by kiyoya** [comment]
My best guess is because setup.py tries to download missing dependencies by itself and that happens outside the sandbox.
